### ISSUE TITLE
mariaDB 외부연결 문제

### ISSUE THREAD

**Issue by knyoon** [visionWWW/Mimi-Backend#4]
백엔드 연결 시, mariaDB 외부 접속을 위해 시도해본 것들
- 사용자 접근 권한 mariaDB에서 grant문 이용하여 추가
- docker 내부 환경 설정 파일의 bind-address 속성 변경 
   1.  0.0.0.0로 변경 2.각자 피씨 아이피 주소로 변경 3. #주석처리
- docker 내부 네트워크가 열려있지 않은 것이라 판단하여 docker 내부 네트워크 추가
- docker subnet 입력

![캡처](https://user-images.githubusercontent.com/80137728/135457535-239f367e-6740-4c91-86cb-bda6249e9840.PNG)

접속오류가 있습니다.

**Comment by eastflag** [comment]
RDS로 연결하는거니?
host에는 RDS라면 해당 url이나 ip를 넣어야 될거 같은데, snowdb라고 넣은거 같은데,

2021년 9월 30일 (목) 오후 9:47, knyoon ***@***.***>님이 작성:
