### ISSUE TITLE
Many To Many 중간 테이블 생성 후 Controller 관련 문제 질문 드립니다!

### ISSUE THREAD

**Issue by visionWWW** [visionWWW/Mimi-Backend#5]
Many To Many 중간 테이블 생성 후 Controller 생성하는 법을 잘 모르겠습니다.

```typescript
@ManyToMany(() => Hashtag, hashtag =>hashtag.id)
@JoinTable()
hashtag: Hashtag[];
```

Review테이블과  hashtag테이블을 연결하는 중에 중간 테이블로 review_hashtag_hashtag가 만들어졌습니다.

![image](https://user-images.githubusercontent.com/62435316/136408801-713dd4c3-90e4-4c14-8a0e-7749efae94fb.png)

그래서 해당 테이블의 Controller로 데이터를 넣으려고 하는데 src/entity에 관련된 테이블이 없어서 데이터를 어떻게 넣어야할 지 모르겠습니다.
Foreign Key 처리에 대한 도움을 주시면 감사하겠습니다.

**Comment by eastflag** [comment]
일단 먼저 entity에 테이블을 모두 설계해야 하는데 db에다가 테이블을 만든거 같은데,,,
db에 answer 테이블을 만들지 말고 entity에 answer 엔티티를 만들고,
마찬가지로 food, restaurant도 그렇고,
엔티티를 설계한 다음에 관계를 정의해야 하는데, review와 hashtag가 many to many 관계라면
https://eastflag.co.kr/fullstack/rest-with-nodejs/react-rest_auth_entity/
여기를 참고해서 관계를 정의해,
그러면 매핑 테이블이 자동으로 생성될거야,
그러니까 db에 임의로 만든 answer, food restaurant review_hashtag_hashtag 테이블은 삭제하고,

엔티티 설계한 다음에 controller에서 데이터를 어떻게 보내는지 얘기해주면 어떻게 넣는지 알려줄께...

2021년 10월 7일 (목) 오후 11:51, ChaeYeong ***@***.***>님이 작성:
